# config/packages/security.yaml
security:
    firewalls:
        # the order in which firewalls are defined is very important, as the
        # request will be handled by the first firewall whose pattern matches
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # a firewall with no pattern should be defined last because it will match all requests
        main:
            lazy: true
            custom_authenticator: App\Security\SecurityAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
            # provider that you set earlier inside providers
            #provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html

            # switch_user: true
    access_control:
      # require ROLE_ADMIN for /admin*
      - { path: '^/cabinet', roles: ROLE_SUPER_ADMIN }
      - { path: '^/controleur/centrale', roles: ROLE_CONTROLEUR_CENTRALE }


    role_hierarchy:
        ROLE_AGENT: ROLE_USER
        ROLE_CONTROLEUR_CENTRALE: [ROLE_AGENT]
        ROLE_SUPER_ADMIN: [ ROLE_CABINET,  ROLE_CONTROLEUR_CENTRALE]