<?php

namespace ContainerSLxvSq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGKat1tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qGKat1t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qGKat1t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contributeurRepo' => ['privates', 'App\\Repository\\ContributeursRepository', 'getContributeursRepositoryService', true],
            'paiementRepo' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
        ], [
            'contributeurRepo' => 'App\\Repository\\ContributeursRepository',
            'paiementRepo' => 'App\\Repository\\PaiementRepository',
        ]);
    }
}
