<?php

namespace ContainerSLxvSq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContributeursService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DV3a3et.App\Entity\Contributeurs' shared service.
     *
     * @return \App\Entity\Contributeurs
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DV3a3et": it references class "App\\Entity\\Contributeurs" but no such service exists.');
    }
}
