<?php

namespace ContainerSLxvSq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\HomeController' shared autowired service.
     *
     * @return \App\Controller\HomeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'HomeController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CalculTaxeMunicipal.php';

        $container->services['App\\Controller\\HomeController'] = $instance = new \App\Controller\HomeController(new \App\Service\CalculTaxeMunicipal(($container->privates['App\\Repository\\ImpotCFNPBRepository'] ?? $container->load('getImpotCFNPBRepositoryService')), ($container->privates['App\\Repository\\ImpotCFPBRepository'] ?? $container->load('getImpotCFPBRepositoryService')), ($container->privates['App\\Repository\\ImpotTOMRepository'] ?? $container->load('getImpotTOMRepositoryService')), ($container->privates['App\\Repository\\RecetteRepository'] ?? $container->load('getRecetteRepositoryService')), ($container->privates['App\\Repository\\RistournesRepository'] ?? $container->load('getRistournesRepositoryService')), ($container->privates['App\\Repository\\ExcedentsRepository'] ?? $container->load('getExcedentsRepositoryService')), ($container->privates['App\\Repository\\PatenteRepository'] ?? $container->load('getPatenteRepositoryService')), ($container->privates['App\\Repository\\TaxIndirecteRepository'] ?? $container->load('getTaxIndirecteRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\HomeController', $container));

        return $instance;
    }
}
