<?php

namespace ContainerSLxvSq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImpotCFPBControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImpotCFPBController' shared autowired service.
     *
     * @return \App\Controller\ImpotCFPBController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ImpotCFPBController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ressources'.\DIRECTORY_SEPARATOR.'CfpbService.php';

        $container->services['App\\Controller\\ImpotCFPBController'] = $instance = new \App\Controller\ImpotCFPBController(new \App\Service\Ressources\CfpbService(($container->privates['App\\Repository\\ImpotCFPBRepository'] ?? $container->load('getImpotCFPBRepositoryService')), ($container->privates['App\\Repository\\ProprieteRepository'] ?? $container->load('getProprieteRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ImpotCFPBController', $container));

        return $instance;
    }
}
