<?php

namespace ContainerSLxvSq8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeImpotsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TypeImpotsController' shared autowired service.
     *
     * @return \App\Controller\TypeImpotsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'TypeImpotsController.php';

        $container->services['App\\Controller\\TypeImpotsController'] = $instance = new \App\Controller\TypeImpotsController(($container->privates['App\\Service\\TaxCalculator'] ?? $container->load('getTaxCalculatorService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\TypeImpotsController', $container));

        return $instance;
    }
}
