<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xtqmpP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xtqmpP/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container0xtqmpP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container0xtqmpP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container0xtqmpP\App_KernelProdContainer([
    'container.build_hash' => '0xtqmpP',
    'container.build_id' => '0d8b053c',
    'container.build_time' => 1721437016,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xtqmpP');
