<?php

namespace ContainerZpZMdJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImpotMiniFiscalControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImpotMiniFiscalController' shared autowired service.
     *
     * @return \App\Controller\ImpotMiniFiscalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ImpotMiniFiscalController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ImpotCapitation'.\DIRECTORY_SEPARATOR.'ImpotMiniFiscalService.php';

        $container->services['App\\Controller\\ImpotMiniFiscalController'] = $instance = new \App\Controller\ImpotMiniFiscalController(new \App\Service\ImpotCapitation\ImpotMiniFiscalService(($container->privates['App\\Repository\\ImpotMiniFiscalRepository'] ?? $container->load('getImpotMiniFiscalRepositoryService')), ($container->privates['App\\Repository\\ProprieteRepository'] ?? $container->load('getProprieteRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ImpotMiniFiscalController', $container));

        return $instance;
    }
}
