<?php

namespace ContainerZpZMdJx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImpotTOMControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImpotTOMController' shared autowired service.
     *
     * @return \App\Controller\ImpotTOMController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ImpotTOMController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Ressources'.\DIRECTORY_SEPARATOR.'TomService.php';

        $container->services['App\\Controller\\ImpotTOMController'] = $instance = new \App\Controller\ImpotTOMController(new \App\Service\Ressources\TomService(($container->privates['App\\Repository\\ImpotTOMRepository'] ?? $container->load('getImpotTOMRepositoryService')), ($container->privates['App\\Repository\\ProprieteRepository'] ?? $container->load('getProprieteRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ImpotTOMController', $container));

        return $instance;
    }
}
