<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BF2iGx7Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.BF2iGx7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BF2iGx7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeImpots' => ['privates', '.errored..service_locator.BF2iGx7.App\\Entity\\TypeImpots', NULL, 'Cannot autowire service ".service_locator.BF2iGx7": it references class "App\\Entity\\TypeImpots" but no such service exists.'],
        ], [
            'typeImpots' => 'App\\Entity\\TypeImpots',
        ]);
    }
}
