<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContributeurControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ContributeurController' shared autowired service.
     *
     * @return \App\Controller\ContributeurController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ContributeurController'] = $instance = new \App\Controller\ContributeurController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ContributeurController', $container));

        return $instance;
    }
}
