<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContributeursRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContributeursRepository' shared autowired service.
     *
     * @return \App\Repository\ContributeursRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContributeursRepository'] = new \App\Repository\ContributeursRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
