<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcedentTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ExcedentType' shared autowired service.
     *
     * @return \App\Form\ExcedentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ExcedentType'] = new \App\Form\ExcedentType();
    }
}
