<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcedentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ExcedentRepository' shared autowired service.
     *
     * @return \App\Repository\ExcedentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ExcedentRepository'] = new \App\Repository\ExcedentRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
