<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImpotTOMTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ImpotTOMType' shared autowired service.
     *
     * @return \App\Form\ImpotTOMType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ImpotTOMType'] = new \App\Form\ImpotTOMType();
    }
}
