<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImpotCFPBControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ImpotCFPBController' shared autowired service.
     *
     * @return \App\Controller\ImpotCFPBController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ImpotCFPBController'] = $instance = new \App\Controller\ImpotCFPBController(new \App\service\CalculService(new \App\service\ImpotCFPBService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')))));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ImpotCFPBController', $container));

        return $instance;
    }
}
