<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImpotTOMControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ImpotTOMController' shared autowired service.
     *
     * @return \App\Controller\ImpotTOMController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ImpotTOMController'] = $instance = new \App\Controller\ImpotTOMController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ImpotTOMController', $container));

        return $instance;
    }
}
