<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRistourneRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RistourneRepository' shared autowired service.
     *
     * @return \App\Repository\RistourneRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RistourneRepository'] = new \App\Repository\RistourneRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
