<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRessourceService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.vxqkg42.App\Entity\Ressource' shared service.
     *
     * @return \App\Entity\Ressource
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vxqkg42": it references class "App\\Entity\\Ressource" but no such service exists.');
    }
}
