<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecetteNonFiscaleTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RecetteNonFiscaleType' shared autowired service.
     *
     * @return \App\Form\RecetteNonFiscaleType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RecetteNonFiscaleType'] = new \App\Form\RecetteNonFiscaleType();
    }
}
