<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\SecurityAuthenticator' shared autowired service.
     *
     * @return \App\Security\SecurityAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\SecurityAuthenticator'] = new \App\Security\SecurityAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
