<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxDetailRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TaxDetailRepository' shared autowired service.
     *
     * @return \App\Repository\TaxDetailRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TaxDetailRepository'] = new \App\Repository\TaxDetailRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
