<?php

namespace Container0xtqmpP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeImpotsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.BF2iGx7.App\Entity\TypeImpots' shared service.
     *
     * @return \App\Entity\TypeImpots
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BF2iGx7": it references class "App\\Entity\\TypeImpots" but no such service exists.');
    }
}
