<?php

namespace ContainerXEKI5Hm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxCalculatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TaxCalculator' shared autowired service.
     *
     * @return \App\Service\TaxCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TaxCalculator.php';

        return $container->privates['App\\Service\\TaxCalculator'] = new \App\Service\TaxCalculator(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
