# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:    

services:

    App\Service\Ressources\TaxIndirecteService:
        arguments:
            
    App\Service\Ressources\PatenteService:
        arguments:
    App\Service\RistournesService:
        arguments:

    App\Service\RecetteService:
        arguments:


    App\Service\ImpotCapitation\ImpotMiniFiscalService:
        arguments:


    App\Service\ImpotCapitation\TaxeRuraleService:
        arguments:

    App\Service\Ressources\TomService:
        arguments:


    App\Service\Ressources\CfpbService:
        arguments:


    App\Service\Ressources\CfnpbService:
        arguments:

            

    App\Service\ExcedentsService:
        arguments:
    App\Service\CalculateurAgentContribuableSiteService:
        arguments:



    App\Service\TaxCalculator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\ImpotService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $impotCFNPBRepository: '@App\Repository\ImpotCFNPBRepository'

    App\Service\CalculTaxeMunicipal:
        arguments:
            $impotCFNPBRepository: '@App\Repository\ImpotCFNPBRepository'
            $impotCFPBRepository: '@App\Repository\ImpotCFPBRepository'
            $impotTOMRepository: '@App\Repository\ImpotTOMRepository'
            $recetteRepository: '@App\Repository\RecetteRepository'
            $ristournesRepository: '@App\Repository\RistournesRepository'
            $excedentsRepository: '@App\Repository\ExcedentsRepository'
            $patenteRepository: '@App\Repository\PatenteRepository'
            $taxIndirectRepository: '@App\Repository\TaxIndirecteRepository'

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
