<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpZMdJx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpZMdJx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZpZMdJx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZpZMdJx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZpZMdJx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZpZMdJx',
    'container.build_id' => 'a3d6579d',
    'container.build_time' => 1722542766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpZMdJx');
