<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SiteCollecte extends \App\Entity\SiteCollecte implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'montantJournalier', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'montantMensuel', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'montantAnnuel', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'contributeurs', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'recetteNonFiscales', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'ristournes', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'excedents', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'impots'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'montantJournalier', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'montantMensuel', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'montantAnnuel', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'contributeurs', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'recetteNonFiscales', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'ristournes', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'excedents', '' . "\0" . 'App\\Entity\\SiteCollecte' . "\0" . 'impots'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SiteCollecte $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantJournalier(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantJournalier', []);

        return parent::getMontantJournalier();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantJournalier(string $montantJournalier): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantJournalier', [$montantJournalier]);

        return parent::setMontantJournalier($montantJournalier);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantMensuel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantMensuel', []);

        return parent::getMontantMensuel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantMensuel(string $montantMensuel): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantMensuel', [$montantMensuel]);

        return parent::setMontantMensuel($montantMensuel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantAnnuel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantAnnuel', []);

        return parent::getMontantAnnuel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantAnnuel(string $montantAnnuel): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantAnnuel', [$montantAnnuel]);

        return parent::setMontantAnnuel($montantAnnuel);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getContributeurs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContributeurs', []);

        return parent::getContributeurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addContributeur(\App\Entity\Contributeurs $contributeur): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContributeur', [$contributeur]);

        return parent::addContributeur($contributeur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContributeur(\App\Entity\Contributeurs $contributeur): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContributeur', [$contributeur]);

        return parent::removeContributeur($contributeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecetteNonFiscales(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecetteNonFiscales', []);

        return parent::getRecetteNonFiscales();
    }

    /**
     * {@inheritDoc}
     */
    public function addRecetteNonFiscale(\App\Entity\RecetteNonFiscale $recetteNonFiscale): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecetteNonFiscale', [$recetteNonFiscale]);

        return parent::addRecetteNonFiscale($recetteNonFiscale);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecetteNonFiscale(\App\Entity\RecetteNonFiscale $recetteNonFiscale): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecetteNonFiscale', [$recetteNonFiscale]);

        return parent::removeRecetteNonFiscale($recetteNonFiscale);
    }

    /**
     * {@inheritDoc}
     */
    public function getRistournes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRistournes', []);

        return parent::getRistournes();
    }

    /**
     * {@inheritDoc}
     */
    public function addRistourne(\App\Entity\Ristourne $ristourne): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRistourne', [$ristourne]);

        return parent::addRistourne($ristourne);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRistourne(\App\Entity\Ristourne $ristourne): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRistourne', [$ristourne]);

        return parent::removeRistourne($ristourne);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcedents(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcedents', []);

        return parent::getExcedents();
    }

    /**
     * {@inheritDoc}
     */
    public function addExcedent(\App\Entity\Excedent $excedent): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExcedent', [$excedent]);

        return parent::addExcedent($excedent);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExcedent(\App\Entity\Excedent $excedent): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExcedent', [$excedent]);

        return parent::removeExcedent($excedent);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpots(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpots', []);

        return parent::getImpots();
    }

    /**
     * {@inheritDoc}
     */
    public function addImpot(\App\Entity\Impot $impot): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImpot', [$impot]);

        return parent::addImpot($impot);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImpot(\App\Entity\Impot $impot): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImpot', [$impot]);

        return parent::removeImpot($impot);
    }

}
